fix reliance on cdn xml error response

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -26,7 +26,7 @@ jobs:
 
     - name: Install Packages
       run: yarn
-    
+
     # - name: Run Tests
     #   run: yarn test
 
@@ -91,7 +91,7 @@ jobs:
     # Maybe Add the option to push all branches to the CDN but don't NPM package them?
 
     - name: Publish NPM Package
-      env: 
+      env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
       run: yarn publish --tag dev
 
@@ -101,7 +101,7 @@ jobs:
   publish:
     needs: build
     name: Publish Release
-    
+
     if: ${{ startsWith(github.ref, 'refs/tags/v') && github.repository_owner == 'jcu-eresearch' }} # Only Run on a Tag in eResearch Repo
 
     runs-on: ubuntu-latest
@@ -114,9 +114,9 @@ jobs:
         node-version: '14' # Use Latest LTS
         cache: 'yarn'
         registry-url: 'https://registry.npmjs.org'
-    
+
     - name: Build Compare-Semver Workflow Action
-      run: | 
+      run: |
         yarn --cwd './actions/compare-semver'
         yarn --cwd './actions/compare-semver' compile
 
@@ -129,14 +129,14 @@ jobs:
     - name: Get Tag
       run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v*}" >> $GITHUB_ENV
 
+    # Version will be 0.0.0 on non-zero exit code
     - name: Get Latest Release Version
       run: |
-        LATEST_VERSION=$(curl ${{ env.cdn_url }}/latest/version.txt)
-        if [[ "$LATEST_VERSION" =~ .*"xml".* ]]; then LATEST_VERSION="0.0.0"; echo "** EXISTING LATEST VERSION DOESN'T EXIST **"; fi
+        LATEST_VERSION=$(curl -sf ${{ env.cdn_url }}/latest/version.txt || echo "0.0.0")
         echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV;
 
     - name: Compare SemVers (Latest)
-      id: compared_semvers 
+      id: compared_semvers
       uses: ./actions/compare-semver
       with:
         version: ${{ env.RELEASE_VERSION }}
@@ -145,15 +145,13 @@ jobs:
     - name: Get Latest Major Version
       run: |
         LOOKUP_VERSION="${{ steps.compared_semvers.outputs.version-major }}"
-        LATEST_MAJOR_VERSION=$(curl ${{ env.cdn_url }}/$LOOKUP_VERSION/version.txt)
-        if [[ "$LATEST_MAJOR_VERSION" =~ .*"xml".* ]]; then LATEST_MAJOR_VERSION="0.0.0"; echo "** EXISTING MAJOR VERSION ($LOOKUP_VERSION) DOESN'T EXIST **"; fi
+        LATEST_MAJOR_VERSION=$(curl -sf ${{ env.cdn_url }}/$LOOKUP_VERSION/version.txt || echo "0.0.0")
         echo "LATEST_MAJOR_VERSION=$LATEST_MAJOR_VERSION" >> $GITHUB_ENV;
 
     - name: Get Latest Minor Version
       run: |
         LOOKUP_VERSION="${{ steps.compared_semvers.outputs.version-major }}.${{ steps.compared_semvers.outputs.version-minor }}"
-        LATEST_MINOR_VERSION=$(curl ${{ env.cdn_url }}/$LOOKUP_VERSION/version.txt)
-        if [[ "$LATEST_MINOR_VERSION" =~ .*"xml".* ]]; then LATEST_MINOR_VERSION="0.0.0"; echo "** EXISTING MINOR VERSION ($LOOKUP_VERSION) DOESN'T EXIST **"; fi
+        LATEST_MINOR_VERSION=$(curl -sf ${{ env.cdn_url }}/$LOOKUP_VERSION/version.txt || echo "0.0.0")
         echo "LATEST_MINOR_VERSION=$LATEST_MINOR_VERSION" >> $GITHUB_ENV;
 
     # Our CDN's S3 Throws an XML Exception Page When no Files are found
@@ -171,7 +169,7 @@ jobs:
       with:
         version: ${{ env.RELEASE_VERSION }}
         compare: ${{ env.LATEST_MINOR_VERSION }}
-   
+
     # Patch, Release and Builds are Specifically chosen
 
     - name: Output Distributed Version
@@ -208,7 +206,7 @@ jobs:
         AWS_REGION: 'ap-southeast-2'
         SOURCE_DIR: 'dist'
         DEST_DIR: 'public/${{ steps.compared_semvers_major.outputs.version-major }}'
-    
+
     - name: Upload to Minor Version on CDN (x.x)
       if: ${{ steps.compared_semvers_minor.outputs.version-is-latest == 'true' && steps.compared_semvers_minor.outputs.version-prerelease == null && steps.compared_semvers_minor.outputs.version-build == null }}
       uses: jakejarvis/s3-sync-action@master
@@ -220,7 +218,7 @@ jobs:
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: 'ap-southeast-2'
         SOURCE_DIR: 'dist'
-        DEST_DIR: 'public/${{ steps.compared_semvers_minor.outputs.version-major }}.${{ steps.compared_semvers_minor.outputs.version-minor }}' 
+        DEST_DIR: 'public/${{ steps.compared_semvers_minor.outputs.version-major }}.${{ steps.compared_semvers_minor.outputs.version-minor }}'
 
     - name: Upload to Latest Release on CDN
       if: ${{ steps.compared_semvers.outputs.version-is-latest == 'true' && steps.compared_semvers.outputs.version-prerelease == null && steps.compared_semvers.outputs.version-build == null }}
@@ -236,8 +234,7 @@ jobs:
         DEST_DIR: 'public/latest'
 
     - name: Publish NPM Package
-      env: 
+      env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
       run: yarn publish
-        
-        
+
